#!/usr/bin/python3
from sys import argv
from math import sqrt


def factor():
    with open(argv[1]) as f:
        for l in f:
            n = int(l)
            print("{:d}=".format(n), end="")
            if n % 2 == 0:
                print("{}*2".format(n//2))
                continue
            sqr = int(sqrt(n))
            if sqr % 2 == 0:
                sqr += 1
            for i in range(3, sqr + 1, 2):
                if n % i == 0:
                    print("{}*{}".format(i, n//i))
                    break
            if n % i != 0:
                print("{}={}*1".format(n, n))


factor()
