#!/usr/bin/python3
"""
Factorize numbers
"""
import sys


def factorize():
    """
    function factorize the number
    """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for l_n in f:
                l_n = int(l_n)
                if l_n % 2 == 0:
                        print("{}={}*{}".format(l_n, l_n // 2, 2))
                        continue
                i = 3
                while i < l_n // 2:
                    if l_n % i == 0:
                        print("{}={}*{}".format(l_n, l_n // i, i))
                        break
                    i = i + 2
                if i == (l_n // 2) + 1:
                    print("{}={}*{}".format(l_n, l_n, 1))
    except (IndexError):
        pass


factorize()
              
